### ISSUE TITLE
talent

### ISSUE THREAD

**Issue by kep123** [grimgravy/wow-armory#2]
Unable to get talent points
‘spec’ → `specMask` 
primary → secondary

**Comment by grimgravy** [comment]
as well? can show me an image or the specific location of the problem.

**Comment by kep123** [comment]
sunwell core ，The talent saved is 1 and 2
TRINITY core，The talent saved is 0 and 1
How to modify, I can not modify the success  class.characters.php

**Comment by kep123** [comment]
I don't know how to upload screenshots on this site

**Comment by grimgravy** [comment]
It's because you do not have permission to modify

**Comment by grimgravy** [comment]
it is?
![sem titulo](https://user-images.githubusercontent.com/2193800/31786533-4668ce78-b4df-11e7-8ce5-0ac2d6e549ac.png)
